# Generated by Django 4.1.4 on 2023-01-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contracting.task'),
        ),
    ]
